export const barData = [{
    show: true,
    labelName: "瓷砖",
    id: 1
}, {
    show: false,
    labelName: "地板",
    id: 2
}, {
    show: false,
    labelName: "卫浴洁具",
    id: 3
}, {
    show: false,
    labelName: "卫浴五金",
    id: 4
}, {
    show: false,
    labelName: "集成吊顶",
    id: 5
}, {
    show: false,
    labelName: "木门",
    id: 6
}, {
    show: false,
    labelName: "橱柜",
    id: 7
}]
